"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Image from "next/image";

interface ProductDetailImageProps {
    images: string[];
    /** Promo badges (super deal / limited stock / discount) overlaid on the image. */
    badges?: React.ReactNode;
}

export default function ProductDetailImage({ images, badges }: ProductDetailImageProps) {
    const [activeIndex, setActiveIndex] = useState(0);

    const handlePrev = () =>
        setActiveIndex((prev) => (prev - 1 + images.length) % images.length);

    const handleNext = () =>
        setActiveIndex((prev) => (prev + 1) % images.length);

    return (
        <div className="flex gap-3 h-full">
            {/* Vertical thumbnail strip */}
            {images.length > 1 && (
                <div className="flex flex-col gap-2.5 overflow-y-auto max-h-[500px] flex-shrink-0">
                    {images.map((img, index) => (
                        <button
                            key={index}
                            onClick={() => setActiveIndex(index)}
                            className={`flex-shrink-0 w-[68px] h-[68px] rounded-xl overflow-hidden transition-all duration-200 ${
                                activeIndex === index
                                    ? "ring-2 ring-[#402F75] ring-offset-1 shadow-md"
                                    : "ring-1 ring-gray-200 bg-white hover:ring-gray-400 opacity-70 hover:opacity-100"
                            }`}
                            aria-label={`View image ${index + 1}`}
                        >
                            <Image
                                src={img}
                                alt={`Thumbnail ${index + 1}`}
                                className="object-contain w-full h-full p-1.5 bg-white"
                                width={68}
                                height={68}
                                unoptimized
                            />
                        </button>
                    ))}
                </div>
            )}

            {/* Main image */}
            <div className="relative flex-1 rounded-2xl bg-white border border-gray-100 overflow-hidden aspect-square flex items-center justify-center group">
                {/* Promo badges — flex row overlaid on the top-left of the image */}
                {badges && (
                    <div className="absolute top-2.5 left-2.5 sm:top-3 sm:left-3 z-20 flex flex-row flex-wrap items-center gap-1.5 sm:gap-2 max-w-[calc(100%-1.25rem)]">
                        {badges}
                    </div>
                )}

                {/* AI-generated image disclaimer (bottom-left so it clears the badges) */}
                <div className="absolute bottom-3 left-3 z-10 flex items-center gap-1 rounded-full bg-black/55 px-2.5 py-1 text-[10px] font-medium text-white backdrop-blur-sm pointer-events-none select-none">
                    <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9z" />
                    </svg>
                    Image generated by AI
                </div>

                <AnimatePresence mode="wait">
                    <motion.div
                        key={activeIndex}
                        initial={{ opacity: 0, scale: 0.96 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 1.02 }}
                        transition={{ duration: 0.22, ease: "easeOut" }}
                        className="absolute inset-0 flex items-center justify-center p-8"
                    >
                        <Image
                            src={images[activeIndex]}
                            alt={`Product image ${activeIndex + 1}`}
                            className="object-contain max-w-full max-h-full"
                            width={540}
                            height={540}
                            unoptimized
                        />
                    </motion.div>
                </AnimatePresence>

                {/* Image counter */}
                {images.length > 1 && (
                    <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex items-center gap-1.5 pointer-events-none">
                        {images.map((_, i) => (
                            <span
                                key={i}
                                className={`block rounded-full transition-all duration-200 ${
                                    i === activeIndex
                                        ? "w-5 h-1.5 bg-[#402F75]"
                                        : "w-1.5 h-1.5 bg-gray-300"
                                }`}
                            />
                        ))}
                    </div>
                )}

                {/* Prev / Next arrows */}
                {images.length > 1 && (
                    <>
                        <button
                            onClick={handlePrev}
                            className="absolute left-3 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full bg-white/90 backdrop-blur-sm border border-gray-200 shadow-sm flex items-center justify-center hover:bg-white opacity-0 group-hover:opacity-100 transition-opacity duration-200"
                            aria-label="Previous image"
                        >
                            <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
                                <path d="M10 12L6 8L10 4" stroke="#374151" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                        </button>
                        <button
                            onClick={handleNext}
                            className="absolute right-3 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full bg-white/90 backdrop-blur-sm border border-gray-200 shadow-sm flex items-center justify-center hover:bg-white opacity-0 group-hover:opacity-100 transition-opacity duration-200"
                            aria-label="Next image"
                        >
                            <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
                                <path d="M6 4L10 8L6 12" stroke="#374151" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                        </button>
                    </>
                )}
            </div>
        </div>
    );
}
