"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Image from "next/image";

interface ProductDetailImageProps {
    images: string[];
    /** Promo badges (super deal / limited stock / discount) overlaid on the image. */
    badges?: React.ReactNode;
}

export default function ProductDetailImage({ images, badges }: ProductDetailImageProps) {
    const [activeIndex, setActiveIndex] = useState(0);

    // Cursor-tracking hover zoom (desktop only — touch never fires mouseenter).
    const [zoom, setZoom] = useState(false);
    const [origin, setOrigin] = useState({ x: 50, y: 50 });
    const handleMove = (e: React.MouseEvent<HTMLDivElement>) => {
        const rect = e.currentTarget.getBoundingClientRect();
        const x = ((e.clientX - rect.left) / rect.width) * 100;
        const y = ((e.clientY - rect.top) / rect.height) * 100;
        setOrigin({ x: Math.max(0, Math.min(100, x)), y: Math.max(0, Math.min(100, y)) });
    };

    const handlePrev = () =>
        setActiveIndex((prev) => (prev - 1 + images.length) % images.length);

    const handleNext = () =>
        setActiveIndex((prev) => (prev + 1) % images.length);

    return (
        <div className="flex gap-3 sm:gap-4 h-full">
            {/* Vertical thumbnail rail */}
            {images.length > 1 && (
                <div className="flex flex-col gap-3 overflow-y-auto max-h-[640px] flex-shrink-0 pr-0.5 -mr-0.5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
                    {images.map((img, index) => (
                        <button
                            key={index}
                            onClick={() => setActiveIndex(index)}
                            className={`flex-shrink-0 w-[64px] sm:w-[76px] h-[64px] sm:h-[76px] rounded-2xl overflow-hidden bg-white transition-all duration-200 ${
                                activeIndex === index
                                    ? "ring-2 ring-[#402F75] ring-offset-2 ring-offset-white shadow-md scale-[1.03]"
                                    : "ring-1 ring-gray-200 opacity-60 hover:opacity-100 hover:ring-[#402F75]/40"
                            }`}
                            aria-label={`View image ${index + 1}`}
                        >
                            <Image
                                src={img}
                                alt={`Thumbnail ${index + 1}`}
                                className="object-contain w-full h-full p-1.5"
                                width={76}
                                height={76}
                                unoptimized
                            />
                        </button>
                    ))}
                </div>
            )}

            {/* Main image */}
            <div
                onMouseEnter={() => setZoom(true)}
                onMouseLeave={() => setZoom(false)}
                onMouseMove={handleMove}
                className="relative flex-1 rounded-[24px] bg-gradient-to-br from-gray-50 to-white border border-gray-100 overflow-hidden aspect-square flex items-center justify-center group cursor-zoom-in"
            >
                {/* Promo badges — flex row overlaid on the top-left of the image */}
                {badges && (
                    <div className="absolute top-3 left-3 sm:top-4 sm:left-4 z-20 flex flex-row flex-wrap items-center gap-1.5 sm:gap-2 max-w-[calc(100%-1.5rem)]">
                        {badges}
                    </div>
                )}

                {/* AI-generated image disclaimer (bottom-left so it clears the badges) */}
                <div className="absolute bottom-3 left-3 z-10 flex items-center gap-1 rounded-full bg-black/55 px-2.5 py-1 text-[10px] font-medium text-white backdrop-blur-sm pointer-events-none select-none">
                    <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9z" />
                    </svg>
                    Image generated by AI
                </div>

                {/* Zoom hint (desktop, fades out on hover) */}
                <div className="absolute top-3 right-3 z-10 hidden sm:flex items-center gap-1 rounded-full bg-white/80 backdrop-blur-sm border border-gray-200 px-2.5 py-1 text-[10px] font-semibold text-gray-500 pointer-events-none select-none opacity-100 group-hover:opacity-0 transition-opacity duration-200">
                    <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <circle cx="11" cy="11" r="7" /><path d="M21 21l-4.3-4.3M11 8v6M8 11h6" />
                    </svg>
                    Hover to zoom
                </div>

                <AnimatePresence mode="wait">
                    <motion.div
                        key={activeIndex}
                        initial={{ opacity: 0, scale: 0.96 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 1.02 }}
                        transition={{ duration: 0.22, ease: "easeOut" }}
                        className="absolute inset-0 flex items-center justify-center p-5 sm:p-7"
                    >
                        <Image
                            src={images[activeIndex]}
                            alt={`Product image ${activeIndex + 1}`}
                            className="object-contain max-w-full max-h-full will-change-transform"
                            width={640}
                            height={640}
                            unoptimized
                            style={{
                                transform: zoom ? "scale(2)" : "scale(1)",
                                transformOrigin: `${origin.x}% ${origin.y}%`,
                                transition: zoom ? "transform 0.12s ease-out" : "transform 0.3s ease-out",
                            }}
                        />
                    </motion.div>
                </AnimatePresence>

                {/* Image counter */}
                {images.length > 1 && (
                    <div className="absolute bottom-4 left-1/2 -translate-x-1/2 z-10 flex items-center gap-1.5 pointer-events-none">
                        {images.map((_, i) => (
                            <span
                                key={i}
                                className={`block rounded-full transition-all duration-200 ${
                                    i === activeIndex
                                        ? "w-5 h-1.5 bg-[#402F75]"
                                        : "w-1.5 h-1.5 bg-gray-300"
                                }`}
                            />
                        ))}
                    </div>
                )}

                {/* Prev / Next arrows */}
                {images.length > 1 && (
                    <>
                        <button
                            onClick={handlePrev}
                            className="absolute left-3 top-1/2 -translate-y-1/2 z-10 w-10 h-10 rounded-full bg-white/90 backdrop-blur-sm border border-gray-200 shadow-sm flex items-center justify-center hover:bg-white hover:scale-105 opacity-0 group-hover:opacity-100 transition-all duration-200"
                            aria-label="Previous image"
                        >
                            <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
                                <path d="M10 12L6 8L10 4" stroke="#374151" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                        </button>
                        <button
                            onClick={handleNext}
                            className="absolute right-3 top-1/2 -translate-y-1/2 z-10 w-10 h-10 rounded-full bg-white/90 backdrop-blur-sm border border-gray-200 shadow-sm flex items-center justify-center hover:bg-white hover:scale-105 opacity-0 group-hover:opacity-100 transition-all duration-200"
                            aria-label="Next image"
                        >
                            <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
                                <path d="M6 4L10 8L6 12" stroke="#374151" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                        </button>
                    </>
                )}
            </div>
        </div>
    );
}
